remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme 
title: Metamorph Arena - Real-time Sports Player Appearance Transformer
description: This is a project proposal by Haram Yoon. It is a innovative computer vision application that transforms sports broadcasts by allowing users to modify players' appearances in real-time as well as upload clips to modify. 